const rarityParser = require('./rarity-parser');

it('parse rarity from adamantine golem', () => {
  const input = `<a target="_blank" href="Images\Monsters\Golem_AdamantineGolem.png"><img class="thumbnail" src="Images\Monsters\Golem_AdamantineGolem.png"></a><span alt="Rare Trait" class="traitrare" title="This rarity indicates that a rules element is very difficult to find in the game world. A rare feat, spell, item or the like is available to players only if the GM decides to include it in the game, typically through discovery during play. Creatures with this trait are rare. They typically can't be summoned. The DC of Recall Knowledge checks related to these creatures is increased by 5."><a href="Traits.aspx?ID=137">Rare</a></span><span alt="Neutral" class="traitalignment" title="Neutral">N</span><span alt="Huge" class="traitsize" title="Huge">Huge</span><span alt="Construct Trait" class="trait" title="A construct is an artificial creature empowered by a force other than necromancy. Constructs are often mindless; they are immune to disease, the paralyzed condition, and poison; and they may have Hardness based on the materials used to construct their bodies. Constructs are not living creatures, nor are they undead. When reduced to 0 Hit Points, a construct creature is destroyed."><a href="Traits.aspx?ID=35">Construct</a></span><span alt="Golem Trait" class="trait" title="Golems are a special type of construct. Golems are immune to almost all magic, but most have a weakness to certain spells."><a href="Traits.aspx?ID=220">Golem</a></span><span alt="Mindless Trait" class="trait" title="A mindless creature has either programmed or rudimentary mental attributes. Most, if not all, of their mental ability modifiers are -5. They are immune to all mental effects."><a href="Traits.aspx?ID=108">Mindless</a></span><br /><b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 189</i></a><br /><b>Perception</b> +26; darkvision<br /><b>Skills</b> <a href="Skills.aspx?ID=3"><u>Athletics</a></u> +38<br /><b>Str</b> +9, <b>Dex</b> -1, <b>Con</b> +9, <b>Int</b> -5, <b>Wis</b> +0, <b>Cha</b> -5`;
  const fields = rarityParser(input);

  expect(fields.rarity).toEqual('Rare');
});

it('parse rarity from aapoph serpentfolk', () => {
  const input = `<a target="_blank" href="Images\Monsters\Serpentfolk_AapophSerpentfolk.png"><img class="thumbnail" src="Images\Monsters\Serpentfolk_AapophSerpentfolk.png"></a><span alt="Uncommon Trait" class="traituncommon" title="Something of uncommon rarity requires special training or comes from a particular culture or part of the world. Some character choices give access to uncommon options, and the GM can choose to allow access for anyone. Less is known about uncommon creatures than common creatures. They typically can't be summoned. The DC of Recall Knowledge checks related to these creature is increased by 2."><a href="Traits.aspx?ID=159">Uncommon</a></span><span alt="Chaotic Evil" class="traitalignment" title="Chaotic Evil">CE</span><span alt="Medium" class="traitsize" title="Medium">Medium</span><span alt="Humanoid Trait" class="trait" title="Humanoid creatures reason and act much like humans. They typically stand upright and have two arms and two legs."><a href="Traits.aspx?ID=91">Humanoid</a></span><span alt="Mutant Trait" class="trait" title="The monster has mutated or evolved, granting it unusual benefits, drawbacks, or both."><a href="Traits.aspx?ID=229">Mutant</a></span><span alt="Serpentfolk Trait" class="trait" title="Serpentfolk are a family of serpentine humanoids."><a href="Traits.aspx?ID=307">Serpentfolk</a></span><br /><b>Source</b> <a href="https://paizo.com/products/btq022yq" target="_blank" class="external-link"><i>Bestiary 2 pg. 238</i></a><br /><b>Perception</b> +8; <a style="text-decoration:underline" href="MonsterAbilities.aspx?ID=12">darkvision</a>, <a style="text-decoration:underline" href="MonsterAbilities.aspx?ID=33">scent (imprecise) 30 feet</a><br /><b>Languages</b> <a href="Languages.aspx?ID=13"><u>Aklo</a></u>, <a href="Languages.aspx?ID=11"><u>Undercommon</a></u>; <a style="text-decoration:underline" href="MonsterAbilities.aspx?ID=37">telepathy 100 feet</a><br /><b>Skills</b> <a href="Skills.aspx?ID=1"><u>Acrobatics</a></u> +7, <a href="Skills.aspx?ID=3"><u>Athletics</a></u> +11, <a href="Skills.aspx?ID=7"><u>Intimidation</a></u> +6<br /><b>Str</b> +4, <b>Dex</b> +2, <b>Con</b> +3, <b>Int</b> -3, <b>Wis</b> +1, <b>Cha</b> -1<br /><b>Items</b> <a href="Weapons.aspx?ID=38"><u>scimitar</u></a>`;
  const fields = rarityParser(input);

  expect(fields.rarity).toEqual('Uncommon');
});