const abilityParser = require('./sense-abilities-parser');
const template = require('./universal-abilities/template');

it('parse sense abilities from grikkitog', () => {
  const input = `<a target="_blank" href="Images\Monsters\Grikkitog.png"><img class="thumbnail" src="Images\Monsters\Grikkitog.png"></a><span alt="Neutral Evil" class="traitalignment" title="Neutral Evil">NE</span><span alt="Huge" class="traitsize" title="Huge">Huge</span><span alt="Aberration Trait" class="trait" title="Aberrations are creatures from beyond the planes or corruptions of the natural order."><a href="Traits.aspx?ID=1">Aberration</a></span><span alt="Earth Trait" class="trait" title="Effects with the earth trait either manipulate or conjure earth. Those that manipulate earth have no effect in an area without earth. Creatures with this trait consist primarily of earth or have a magical connection to that element. Planes with this trait are mostly solid, with caverns and other hollow pockets."><a href="Traits.aspx?ID=55">Earth</a></span><br /><b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 195</i></a><br /><b>Perception</b> +29; darkvision, manifold vision, tremorsense (imprecise) 30 feet<br /><b>Languages</b> <a href="Languages.aspx?ID=22"><u>Terran</a></u><br /><b>Skills</b> <a href="Skills.aspx?ID=3"><u>Athletics</a></u> +28, <a href="Skills.aspx?ID=5"><u>Deception</a></u> +27 (+31 to imitate stone), <a href="Skills.aspx?ID=16"><u>Survival</a></u> +25<br /><b>Str</b> +8, <b>Dex</b> +4, <b>Con</b> +5, <b>Int</b> +2, <b>Wis</b> +5, <b>Cha</b> +5<br /><b>Implant Core</b> <img class="actiondark" alt="Three Actions" style="height:15px; padding:0px 2px 0px 2px" src="Images\Actions\ThreeActions.png"><img class="actionlight" alt="Three Actions" style="height:15px; padding:0px 2px 0px 2px" src="Images\Actions\ThreeActions_I.png"> (<a style="text-decoration:underline" href="Traits.aspx?ID=104">manipulate</a>) The grikkitog implants its core into an adjacent section of earth or stone, melding seamlessly and changing its visual appearance to match the surrounding rock. It's immobilized but automatically succeeds at its Deception check to Impersonate the stone around it; creatures actively searching for it can still attempt Perception checks against its Deception DC as normal. A grikkitog can release its implantation as a free action, which has the manipulate trait. A grikkitog's infestation aura and manifold vision are only active while implanted.<br /> <b>Manifold Vision</b> While its core is implanted, the grikkitog can see through the eyes it creates throughout the area of its infestation aura, gaining the benefits of all-around vision.`;
  const fields = abilityParser(input);

  expect(fields.sense_abilities).toEqual([
    {
      ...template,
      action_cost: 'Three Actions',
      description: `The grikkitog implants its core into an adjacent section of earth or stone, melding seamlessly and changing its visual appearance to match the surrounding rock. It's immobilized but automatically succeeds at its Deception check to Impersonate the stone around it; creatures actively searching for it can still attempt Perception checks against its Deception DC as normal. A grikkitog can release its implantation as a free action, which has the manipulate trait. A grikkitog's infestation aura and manifold vision are only active while implanted.`,
      name: 'Implant Core',
      raw_description: `**Implant Core** [Three Actions] (__manipulate__) The grikkitog implants its core into an adjacent section of earth or stone, melding seamlessly and changing its visual appearance to match the surrounding rock. It's immobilized but automatically succeeds at its Deception check to Impersonate the stone around it; creatures actively searching for it can still attempt Perception checks against its Deception DC as normal. A grikkitog can release its implantation as a free action, which has the manipulate trait. A grikkitog's infestation aura and manifold vision are only active while implanted.`,
      traits: ['manipulate'],
    },
    {
      ...template,
      action_cost: 'None',
      description: 'While its core is implanted, the grikkitog can see through the eyes it creates throughout the area of its infestation aura, gaining the benefits of all-around vision.',
      name: 'Manifold Vision',
      raw_description: `**Manifold Vision** While its core is implanted, the grikkitog can see through the eyes it creates throughout the area of its infestation aura, gaining the benefits of all-around vision.`,
    },
  ]);
});

it('parse sense abilities from werewolf', () => {
  const input = `<a target="_blank" href="Images\Monsters\Werecreature_Werewolf.png"><img class="thumbnail" src="Images\Monsters\Werecreature_Werewolf.png"></a><span alt="Chaotic Evil" class="traitalignment" title="Chaotic Evil">CE</span><span alt="Medium" class="traitsize" title="Medium">Medium</span><span alt="Beast Trait" class="trait" title="A creature similar to an animal but with an Intelligence modifier of -3 or higher is usually a beast. Unlike an animal, a beast might be able to speak and reason."><a href="Traits.aspx?ID=20">Beast</a></span><span alt="Human Trait" class="trait" title="A creature with this trait is a member of the human ancestry. Humans are a diverse array of people known for their adaptability. An ability with this trait can be used or selected only by humans."><a href="Traits.aspx?ID=90">Human</a></span><span alt="Humanoid Trait" class="trait" title="Humanoid creatures reason and act much like humans. They typically stand upright and have two arms and two legs."><a href="Traits.aspx?ID=91">Humanoid</a></span><span alt="Werecreature Trait" class="trait" title="These shapechanging creatures either are naturally able to shift between animal, humanoid, and hybrid forms or are afflicted with a curse that forces them to shift involuntarily."><a href="Traits.aspx?ID=243">Werecreature</a></span><br /><b>Source</b> <a href="https://paizo.com/products/btq01y0m?Pathfinder-Bestiary" target="_blank" class="external-link"><i>Bestiary pg. 330</i></a><br /><b>Perception</b> +9; low-light vision, scent (imprecise) 30 feet<br /><b>Languages</b> <a href="Languages.aspx?ID=1"><u>Common</a></u>; wolf empathy<br /><b>Skills</b> <a href="Skills.aspx?ID=1"><u>Acrobatics</a></u> +7, <a href="Skills.aspx?ID=3"><u>Athletics</a></u> +9, <a href="Skills.aspx?ID=16"><u>Survival</a></u> +10<br /><b>Str</b> +4, <b>Dex</b> +2, <b>Con</b> +2, <b>Int</b> -1, <b>Wis</b> +2, <b>Cha</b> +1<br /><b>Wolf Empathy</b> (<a style="text-decoration:underline" href="Traits.aspx?ID=47">divination</a>, <a style="text-decoration:underline" href="Traits.aspx?ID=134">primal</a>) The werewolf can communicate with lupines.<br /><b>Items</b> <a href="Weapons.aspx?ID=16"><u>battle axe</u></a>, <a href="Weapons.aspx?ID=75"><u>composite shortbow (20 arrows)</u></a>, <a href="Armor.aspx?ID=5"><u>studded leather armor</u></a>`;
  const fields = abilityParser(input);

  const names = fields.sense_abilities.map(x => x.name);

  expect(names).toEqual(['Wolf Empathy']);
});